package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alojamiento generated by hbm2java
 */
@Entity
@Table(name="alojamiento"
    ,catalog="gestionhotel"
)
public class Alojamiento  implements java.io.Serializable {


     private Integer id;
     private Agencia agencia;
     private Reserva reserva;
     private Date fechaEntradaPrevista;
     private Date fechaSalidaPrevista;
     private Date fechaEntrada;
     private Date fechaSalida;
     private String pension;
     private String tipoCama;
     private Integer numeroAdultos;
     private Integer numeroChild;
     private Integer numeroBebes;
     private String prefHabitacion;
     private String prefTipoHabitacion;
     private String prefVistas;
     private String prefTipoCama;
     private String prefTipoRestaurante;
     private String prefTurnoRestaurante;
     private Boolean cuna;
     private Boolean camaExtra;
     private String comentario;
     private int noShow;

    public Alojamiento() {
    }

	
    public Alojamiento(Date fechaEntradaPrevista, Date fechaSalidaPrevista, String pension, int noShow) {
        this.fechaEntradaPrevista = fechaEntradaPrevista;
        this.fechaSalidaPrevista = fechaSalidaPrevista;
        this.pension = pension;
        this.noShow = noShow;
    }
    public Alojamiento(Agencia agencia, Reserva reserva, Date fechaEntradaPrevista, Date fechaSalidaPrevista, Date fechaEntrada, Date fechaSalida, String pension, String tipoCama, Integer numeroAdultos, Integer numeroChild, Integer numeroBebes, String prefHabitacion, String prefTipoHabitacion, String prefVistas, String prefTipoCama, String prefTipoRestaurante, String prefTurnoRestaurante, Boolean cuna, Boolean camaExtra, String comentario, int noShow) {
       this.agencia = agencia;
       this.reserva = reserva;
       this.fechaEntradaPrevista = fechaEntradaPrevista;
       this.fechaSalidaPrevista = fechaSalidaPrevista;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.pension = pension;
       this.tipoCama = tipoCama;
       this.numeroAdultos = numeroAdultos;
       this.numeroChild = numeroChild;
       this.numeroBebes = numeroBebes;
       this.prefHabitacion = prefHabitacion;
       this.prefTipoHabitacion = prefTipoHabitacion;
       this.prefVistas = prefVistas;
       this.prefTipoCama = prefTipoCama;
       this.prefTipoRestaurante = prefTipoRestaurante;
       this.prefTurnoRestaurante = prefTurnoRestaurante;
       this.cuna = cuna;
       this.camaExtra = camaExtra;
       this.comentario = comentario;
       this.noShow = noShow;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_habitacion")
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_reserva")
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_entrada_prevista", nullable=false, length=10)
    public Date getFechaEntradaPrevista() {
        return this.fechaEntradaPrevista;
    }
    
    public void setFechaEntradaPrevista(Date fechaEntradaPrevista) {
        this.fechaEntradaPrevista = fechaEntradaPrevista;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_salida_prevista", nullable=false, length=10)
    public Date getFechaSalidaPrevista() {
        return this.fechaSalidaPrevista;
    }
    
    public void setFechaSalidaPrevista(Date fechaSalidaPrevista) {
        this.fechaSalidaPrevista = fechaSalidaPrevista;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_entrada", length=10)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_salida", length=10)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    
    @Column(name="pension", nullable=false, length=40)
    public String getPension() {
        return this.pension;
    }
    
    public void setPension(String pension) {
        this.pension = pension;
    }

    
    @Column(name="tipo_cama", length=40)
    public String getTipoCama() {
        return this.tipoCama;
    }
    
    public void setTipoCama(String tipoCama) {
        this.tipoCama = tipoCama;
    }

    
    @Column(name="numero_adultos")
    public Integer getNumeroAdultos() {
        return this.numeroAdultos;
    }
    
    public void setNumeroAdultos(Integer numeroAdultos) {
        this.numeroAdultos = numeroAdultos;
    }

    
    @Column(name="numero_child")
    public Integer getNumeroChild() {
        return this.numeroChild;
    }
    
    public void setNumeroChild(Integer numeroChild) {
        this.numeroChild = numeroChild;
    }

    
    @Column(name="numero_bebes")
    public Integer getNumeroBebes() {
        return this.numeroBebes;
    }
    
    public void setNumeroBebes(Integer numeroBebes) {
        this.numeroBebes = numeroBebes;
    }

    
    @Column(name="pref_habitacion", length=40)
    public String getPrefHabitacion() {
        return this.prefHabitacion;
    }
    
    public void setPrefHabitacion(String prefHabitacion) {
        this.prefHabitacion = prefHabitacion;
    }

    
    @Column(name="pref_tipo_habitacion", length=40)
    public String getPrefTipoHabitacion() {
        return this.prefTipoHabitacion;
    }
    
    public void setPrefTipoHabitacion(String prefTipoHabitacion) {
        this.prefTipoHabitacion = prefTipoHabitacion;
    }

    
    @Column(name="pref_vistas", length=40)
    public String getPrefVistas() {
        return this.prefVistas;
    }
    
    public void setPrefVistas(String prefVistas) {
        this.prefVistas = prefVistas;
    }

    
    @Column(name="pref_tipo_cama", length=40)
    public String getPrefTipoCama() {
        return this.prefTipoCama;
    }
    
    public void setPrefTipoCama(String prefTipoCama) {
        this.prefTipoCama = prefTipoCama;
    }

    
    @Column(name="pref_tipo_restaurante", length=40)
    public String getPrefTipoRestaurante() {
        return this.prefTipoRestaurante;
    }
    
    public void setPrefTipoRestaurante(String prefTipoRestaurante) {
        this.prefTipoRestaurante = prefTipoRestaurante;
    }

    
    @Column(name="pref_turno_restaurante")
    public String getPrefTurnoRestaurante() {
        return this.prefTurnoRestaurante;
    }
    
    public void setPrefTurnoRestaurante(String prefTurnoRestaurante) {
        this.prefTurnoRestaurante = prefTurnoRestaurante;
    }

    
    @Column(name="cuna")
    public Boolean getCuna() {
        return this.cuna;
    }
    
    public void setCuna(Boolean cuna) {
        this.cuna = cuna;
    }

    
    @Column(name="cama_extra")
    public Boolean getCamaExtra() {
        return this.camaExtra;
    }
    
    public void setCamaExtra(Boolean camaExtra) {
        this.camaExtra = camaExtra;
    }

    
    @Column(name="comentario", length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="no_show", nullable=false)
    public int getNoShow() {
        return this.noShow;
    }
    
    public void setNoShow(int noShow) {
        this.noShow = noShow;
    }




}


