package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DetallesReserva generated by hbm2java
 */
public class DetallesReserva  implements java.io.Serializable {


     private int idDetallesReserva;
     private Habitacion habitacion;
     private Reserva reserva;
     private String nombreReserva;
     private Integer cantidadHuespedes;
     private Date fechaEntradaPrevista;
     private Date fechaSalidaPrevista;
     private Date fechaEntrada;
     private Date fechaSalida;
     private Set huespedHabitacions = new HashSet(0);

    public DetallesReserva() {
    }

	
    public DetallesReserva(int idDetallesReserva, Reserva reserva, Date fechaEntradaPrevista, Date fechaSalidaPrevista) {
        this.idDetallesReserva = idDetallesReserva;
        this.reserva = reserva;
        this.fechaEntradaPrevista = fechaEntradaPrevista;
        this.fechaSalidaPrevista = fechaSalidaPrevista;
    }
    public DetallesReserva(int idDetallesReserva, Habitacion habitacion, Reserva reserva, String nombreReserva, Integer cantidadHuespedes, Date fechaEntradaPrevista, Date fechaSalidaPrevista, Date fechaEntrada, Date fechaSalida, Set huespedHabitacions) {
       this.idDetallesReserva = idDetallesReserva;
       this.habitacion = habitacion;
       this.reserva = reserva;
       this.nombreReserva = nombreReserva;
       this.cantidadHuespedes = cantidadHuespedes;
       this.fechaEntradaPrevista = fechaEntradaPrevista;
       this.fechaSalidaPrevista = fechaSalidaPrevista;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.huespedHabitacions = huespedHabitacions;
    }
   
    public int getIdDetallesReserva() {
        return this.idDetallesReserva;
    }
    
    public void setIdDetallesReserva(int idDetallesReserva) {
        this.idDetallesReserva = idDetallesReserva;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public String getNombreReserva() {
        return this.nombreReserva;
    }
    
    public void setNombreReserva(String nombreReserva) {
        this.nombreReserva = nombreReserva;
    }
    public Integer getCantidadHuespedes() {
        return this.cantidadHuespedes;
    }
    
    public void setCantidadHuespedes(Integer cantidadHuespedes) {
        this.cantidadHuespedes = cantidadHuespedes;
    }
    public Date getFechaEntradaPrevista() {
        return this.fechaEntradaPrevista;
    }
    
    public void setFechaEntradaPrevista(Date fechaEntradaPrevista) {
        this.fechaEntradaPrevista = fechaEntradaPrevista;
    }
    public Date getFechaSalidaPrevista() {
        return this.fechaSalidaPrevista;
    }
    
    public void setFechaSalidaPrevista(Date fechaSalidaPrevista) {
        this.fechaSalidaPrevista = fechaSalidaPrevista;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Set getHuespedHabitacions() {
        return this.huespedHabitacions;
    }
    
    public void setHuespedHabitacions(Set huespedHabitacions) {
        this.huespedHabitacions = huespedHabitacions;
    }




}


