package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturaArticuloId generated by hbm2java
 */
@Embeddable
public class FacturaArticuloId  implements java.io.Serializable {


     private int fkFactura;
     private int fkArticulo;

    public FacturaArticuloId() {
    }

    public FacturaArticuloId(int fkFactura, int fkArticulo) {
       this.fkFactura = fkFactura;
       this.fkArticulo = fkArticulo;
    }
   


    @Column(name="fk_factura", nullable=false)
    public int getFkFactura() {
        return this.fkFactura;
    }
    
    public void setFkFactura(int fkFactura) {
        this.fkFactura = fkFactura;
    }


    @Column(name="fk_articulo", nullable=false)
    public int getFkArticulo() {
        return this.fkArticulo;
    }
    
    public void setFkArticulo(int fkArticulo) {
        this.fkArticulo = fkArticulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaArticuloId) ) return false;
		 FacturaArticuloId castOther = ( FacturaArticuloId ) other; 
         
		 return (this.getFkFactura()==castOther.getFkFactura())
 && (this.getFkArticulo()==castOther.getFkArticulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkFactura();
         result = 37 * result + this.getFkArticulo();
         return result;
   }   


}


