package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FacturaArticulo generated by hbm2java
 */
@Entity
@Table(name="factura_articulo"
    ,catalog="gestionhotel"
)
public class FacturaArticulo  implements java.io.Serializable {


     private FacturaArticuloId id;

    public FacturaArticulo() {
    }

    public FacturaArticulo(FacturaArticuloId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkFactura", column=@Column(name="fk_factura", nullable=false) ), 
        @AttributeOverride(name="fkArticulo", column=@Column(name="fk_articulo", nullable=false) ) } )
    public FacturaArticuloId getId() {
        return this.id;
    }
    
    public void setId(FacturaArticuloId id) {
        this.id = id;
    }




}


