package gestionhotel.zapto.org.gestionhotelcliente.modelos.Pojos;
// Generated 09-mar-2018 17:01:24 by Hibernate Tools 4.3.1


import gestionhotel.zapto.org.gestionhotelcliente.modelos.Pojos.Tipo;
import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int idHabitacion;
     private Tipo tipo;
     private String descripcion;
     private Boolean limpiar;
     private Short camaExtra;
     private Set detallesReservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Habitacion(int idHabitacion, Tipo tipo, String descripcion, Boolean limpiar, Short camaExtra, Set detallesReservas) {
       this.idHabitacion = idHabitacion;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.limpiar = limpiar;
       this.camaExtra = camaExtra;
       this.detallesReservas = detallesReservas;
    }
   
    public int getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getLimpiar() {
        return this.limpiar;
    }
    
    public void setLimpiar(Boolean limpiar) {
        this.limpiar = limpiar;
    }
    public Short getCamaExtra() {
        return this.camaExtra;
    }
    
    public void setCamaExtra(Short camaExtra) {
        this.camaExtra = camaExtra;
    }
    public Set getDetallesReservas() {
        return this.detallesReservas;
    }
    
    public void setDetallesReservas(Set detallesReservas) {
        this.detallesReservas = detallesReservas;
    }




}


