package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Habitacion generated by hbm2java
 */
@Entity
@Table(name="habitacion"
    ,catalog="gestionhotel"
)
public class Habitacion  implements java.io.Serializable {


     private String numero;
     private Trabajador trabajador;
     private String descripcion;
     private String comentario;
     private String vistas;
     private String tipoCama;
     private String estado;

    public Habitacion() {
    }

    public Habitacion(String numero, Trabajador trabajador, String descripcion, String comentario, String vistas, String tipoCama, String estado) {
       this.numero = numero;
       this.trabajador = trabajador;
       this.descripcion = descripcion;
       this.comentario = comentario;
       this.vistas = vistas;
       this.tipoCama = tipoCama;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="numero", unique=true, nullable=false, length=10)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_tipo_habitacion", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="descripcion", nullable=false, length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="comentario", nullable=false, length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="vistas", nullable=false, length=40)
    public String getVistas() {
        return this.vistas;
    }
    
    public void setVistas(String vistas) {
        this.vistas = vistas;
    }

    
    @Column(name="tipo_cama", nullable=false, length=40)
    public String getTipoCama() {
        return this.tipoCama;
    }
    
    public void setTipoCama(String tipoCama) {
        this.tipoCama = tipoCama;
    }

    
    @Column(name="estado", nullable=false, length=40)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


