package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 05-jun-2018 18:15:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int numero;
     private String descripcion;
     private String tipo;
     private Byte limpiar;
     private Byte camaExtra;
     private String comentario;
     private String vistas;
     private String tipoCama;
     private String estado;
     private Set detallesReservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int numero, String comentario, String vistas, String tipoCama, String estado) {
        this.numero = numero;
        this.comentario = comentario;
        this.vistas = vistas;
        this.tipoCama = tipoCama;
        this.estado = estado;
    }
    public Habitacion(int numero, String descripcion, String tipo, Byte limpiar, Byte camaExtra, String comentario, String vistas, String tipoCama, String estado, Set detallesReservas) {
       this.numero = numero;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.limpiar = limpiar;
       this.camaExtra = camaExtra;
       this.comentario = comentario;
       this.vistas = vistas;
       this.tipoCama = tipoCama;
       this.estado = estado;
       this.detallesReservas = detallesReservas;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Byte getLimpiar() {
        return this.limpiar;
    }
    
    public void setLimpiar(Byte limpiar) {
        this.limpiar = limpiar;
    }
    public Byte getCamaExtra() {
        return this.camaExtra;
    }
    
    public void setCamaExtra(Byte camaExtra) {
        this.camaExtra = camaExtra;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getVistas() {
        return this.vistas;
    }
    
    public void setVistas(String vistas) {
        this.vistas = vistas;
    }
    public String getTipoCama() {
        return this.tipoCama;
    }
    
    public void setTipoCama(String tipoCama) {
        this.tipoCama = tipoCama;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetallesReservas() {
        return this.detallesReservas;
    }
    
    public void setDetallesReservas(Set detallesReservas) {
        this.detallesReservas = detallesReservas;
    }




}


