package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1



/**
 * HuespedHabitacion generated by hbm2java
 */
public class HuespedHabitacion  implements java.io.Serializable {


     private int idHuespedHabitacion;
     private DetallesReserva detallesReserva;
     private Persona persona;

    public HuespedHabitacion() {
    }

    public HuespedHabitacion(int idHuespedHabitacion, DetallesReserva detallesReserva, Persona persona) {
       this.idHuespedHabitacion = idHuespedHabitacion;
       this.detallesReserva = detallesReserva;
       this.persona = persona;
    }
   
    public int getIdHuespedHabitacion() {
        return this.idHuespedHabitacion;
    }
    
    public void setIdHuespedHabitacion(int idHuespedHabitacion) {
        this.idHuespedHabitacion = idHuespedHabitacion;
    }
    public DetallesReserva getDetallesReserva() {
        return this.detallesReserva;
    }
    
    public void setDetallesReserva(DetallesReserva detallesReserva) {
        this.detallesReserva = detallesReserva;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }




}


