package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 05-jun-2018 18:15:23 by Hibernate Tools 4.3.1



/**
 * HuespedHabitacion generated by hbm2java
 */
public class HuespedHabitacion  implements java.io.Serializable {


     private Integer idHuespedHabitacion;
     private DetallesReserva detallesReserva;
     private Persona persona;
     private String comentario;

    public HuespedHabitacion() {
    }

    public HuespedHabitacion(DetallesReserva detallesReserva, Persona persona, String comentario) {
       this.detallesReserva = detallesReserva;
       this.persona = persona;
       this.comentario = comentario;
    }
   
    public Integer getIdHuespedHabitacion() {
        return this.idHuespedHabitacion;
    }
    
    public void setIdHuespedHabitacion(Integer idHuespedHabitacion) {
        this.idHuespedHabitacion = idHuespedHabitacion;
    }
    public DetallesReserva getDetallesReserva() {
        return this.detallesReserva;
    }
    
    public void setDetallesReserva(DetallesReserva detallesReserva) {
        this.detallesReserva = detallesReserva;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


