package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Huesped generated by hbm2java
 */
@Entity
@Table(name="huesped"
    ,catalog="gestionhotel"
)
public class Huesped  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private Boolean repetidor;
     private boolean dentro;

    public Huesped() {
    }

	
    public Huesped(Persona persona, boolean dentro) {
        this.persona = persona;
        this.dentro = dentro;
    }
    public Huesped(Persona persona, Boolean repetidor, boolean dentro) {
       this.persona = persona;
       this.repetidor = repetidor;
       this.dentro = dentro;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="repetidor")
    public Boolean getRepetidor() {
        return this.repetidor;
    }
    
    public void setRepetidor(Boolean repetidor) {
        this.repetidor = repetidor;
    }

    
    @Column(name="dentro", nullable=false)
    public boolean isDentro() {
        return this.dentro;
    }
    
    public void setDentro(boolean dentro) {
        this.dentro = dentro;
    }




}


