package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 28-may-2018 19:38:21 by Hibernate Tools 4.3.1



/**
 * Parentesco generated by hbm2java
 */
public class Parentesco  implements java.io.Serializable {


     private ParentescoId id;
     private Persona personaByCodPariente;
     private Persona personaByCodPersona;
     private String tipoParentesco;
     private String comentario;

    public Parentesco() {
    }

	
    public Parentesco(ParentescoId id, Persona personaByCodPariente, Persona personaByCodPersona, String comentario) {
        this.id = id;
        this.personaByCodPariente = personaByCodPariente;
        this.personaByCodPersona = personaByCodPersona;
        this.comentario = comentario;
    }
    public Parentesco(ParentescoId id, Persona personaByCodPariente, Persona personaByCodPersona, String tipoParentesco, String comentario) {
       this.id = id;
       this.personaByCodPariente = personaByCodPariente;
       this.personaByCodPersona = personaByCodPersona;
       this.tipoParentesco = tipoParentesco;
       this.comentario = comentario;
    }
   
    public ParentescoId getId() {
        return this.id;
    }
    
    public void setId(ParentescoId id) {
        this.id = id;
    }
    public Persona getPersonaByCodPariente() {
        return this.personaByCodPariente;
    }
    
    public void setPersonaByCodPariente(Persona personaByCodPariente) {
        this.personaByCodPariente = personaByCodPariente;
    }
    public Persona getPersonaByCodPersona() {
        return this.personaByCodPersona;
    }
    
    public void setPersonaByCodPersona(Persona personaByCodPersona) {
        this.personaByCodPersona = personaByCodPersona;
    }
    public String getTipoParentesco() {
        return this.tipoParentesco;
    }
    
    public void setTipoParentesco(String tipoParentesco) {
        this.tipoParentesco = tipoParentesco;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


