package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parte generated by hbm2java
 */
@Entity
@Table(name="parte"
    ,catalog="gestionhotel"
)
public class Parte  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private Trabajador trabajador;
     private String categoria;
     private String descripcion;
     private String concepto;
     private String grado;
     private Set personas = new HashSet(0);

    public Parte() {
    }

	
    public Parte(int id, Persona persona, Trabajador trabajador, String categoria, String descripcion, String concepto, String grado) {
        this.id = id;
        this.persona = persona;
        this.trabajador = trabajador;
        this.categoria = categoria;
        this.descripcion = descripcion;
        this.concepto = concepto;
        this.grado = grado;
    }
    public Parte(int id, Persona persona, Trabajador trabajador, String categoria, String descripcion, String concepto, String grado, Set personas) {
       this.id = id;
       this.persona = persona;
       this.trabajador = trabajador;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.concepto = concepto;
       this.grado = grado;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_trabajador", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="categoria", nullable=false, length=40)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="descripcion", nullable=false, length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="concepto", nullable=false, length=40)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="grado", nullable=false, length=40)
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="parte_persona", catalog="gestionhotel", joinColumns = { 
        @JoinColumn(name="fk_parte", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="fk_persona", nullable=false, updatable=false) })
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


