package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="gestionhotel"
    , uniqueConstraints = @UniqueConstraint(columnNames="numero_documento") 
)
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String numeroDocumento;
     private String nombre;
     private String calle;
     private String codPostal;
     private String ciudad;
     private String provincia;
     private String estado;
     private Boolean esEmpresa;
     private String jurNombreComercial;
     private Date fisFechaNacimiento;
     private Integer fisEdad;
     private String fisTratamiento;
     private Boolean fisSexoHombre;
     private String jurRazonSocial;
     private String fisPrimerApellido;
     private String fisSegundoApellido;
     private String fisNacionalidad;
     private String categoria;
     private String pasaporte;
     private String email;
     private String paginaWeb;
     private String comentario;
     private Boolean fisDiscapacitado;
     private String numero;
     private byte[] foto;
     private Set partes = new HashSet(0);
     private Set telefonoPersonas = new HashSet(0);
     private Set trabajadors = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set partes_1 = new HashSet(0);
     private Set proveedors = new HashSet(0);
     private Set agencias = new HashSet(0);
     private Set huespeds = new HashSet(0);

    public Persona() {
    }

    public Persona(String numeroDocumento, String nombre, String calle, String codPostal, String ciudad, String provincia, String estado, Boolean esEmpresa, String jurNombreComercial, Date fisFechaNacimiento, Integer fisEdad, String fisTratamiento, Boolean fisSexoHombre, String jurRazonSocial, String fisPrimerApellido, String fisSegundoApellido, String fisNacionalidad, String categoria, String pasaporte, String email, String paginaWeb, String comentario, Boolean fisDiscapacitado, String numero, byte[] foto, Set partes, Set telefonoPersonas, Set trabajadors, Set clientes, Set partes_1, Set proveedors, Set agencias, Set huespeds) {
       this.numeroDocumento = numeroDocumento;
       this.nombre = nombre;
       this.calle = calle;
       this.codPostal = codPostal;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.estado = estado;
       this.esEmpresa = esEmpresa;
       this.jurNombreComercial = jurNombreComercial;
       this.fisFechaNacimiento = fisFechaNacimiento;
       this.fisEdad = fisEdad;
       this.fisTratamiento = fisTratamiento;
       this.fisSexoHombre = fisSexoHombre;
       this.jurRazonSocial = jurRazonSocial;
       this.fisPrimerApellido = fisPrimerApellido;
       this.fisSegundoApellido = fisSegundoApellido;
       this.fisNacionalidad = fisNacionalidad;
       this.categoria = categoria;
       this.pasaporte = pasaporte;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.comentario = comentario;
       this.fisDiscapacitado = fisDiscapacitado;
       this.numero = numero;
       this.foto = foto;
       this.partes = partes;
       this.telefonoPersonas = telefonoPersonas;
       this.trabajadors = trabajadors;
       this.clientes = clientes;
       this.partes_1 = partes_1;
       this.proveedors = proveedors;
       this.agencias = agencias;
       this.huespeds = huespeds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="numero_documento", unique=true, length=20)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    
    @Column(name="nombre", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="calle", length=40)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="cod_postal", length=20)
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }

    
    @Column(name="ciudad", length=40)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="provincia", length=40)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="estado", length=40)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="es_empresa")
    public Boolean getEsEmpresa() {
        return this.esEmpresa;
    }
    
    public void setEsEmpresa(Boolean esEmpresa) {
        this.esEmpresa = esEmpresa;
    }

    
    @Column(name="jur_nombre_comercial", length=40)
    public String getJurNombreComercial() {
        return this.jurNombreComercial;
    }
    
    public void setJurNombreComercial(String jurNombreComercial) {
        this.jurNombreComercial = jurNombreComercial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fis_fecha_nacimiento", length=10)
    public Date getFisFechaNacimiento() {
        return this.fisFechaNacimiento;
    }
    
    public void setFisFechaNacimiento(Date fisFechaNacimiento) {
        this.fisFechaNacimiento = fisFechaNacimiento;
    }

    
    @Column(name="fis_edad")
    public Integer getFisEdad() {
        return this.fisEdad;
    }
    
    public void setFisEdad(Integer fisEdad) {
        this.fisEdad = fisEdad;
    }

    
    @Column(name="fis_tratamiento", length=40)
    public String getFisTratamiento() {
        return this.fisTratamiento;
    }
    
    public void setFisTratamiento(String fisTratamiento) {
        this.fisTratamiento = fisTratamiento;
    }

    
    @Column(name="fis_sexo_hombre")
    public Boolean getFisSexoHombre() {
        return this.fisSexoHombre;
    }
    
    public void setFisSexoHombre(Boolean fisSexoHombre) {
        this.fisSexoHombre = fisSexoHombre;
    }

    
    @Column(name="jur_razon_social", length=40)
    public String getJurRazonSocial() {
        return this.jurRazonSocial;
    }
    
    public void setJurRazonSocial(String jurRazonSocial) {
        this.jurRazonSocial = jurRazonSocial;
    }

    
    @Column(name="fis_primer_apellido", length=40)
    public String getFisPrimerApellido() {
        return this.fisPrimerApellido;
    }
    
    public void setFisPrimerApellido(String fisPrimerApellido) {
        this.fisPrimerApellido = fisPrimerApellido;
    }

    
    @Column(name="fis_segundo_apellido", length=40)
    public String getFisSegundoApellido() {
        return this.fisSegundoApellido;
    }
    
    public void setFisSegundoApellido(String fisSegundoApellido) {
        this.fisSegundoApellido = fisSegundoApellido;
    }

    
    @Column(name="fis_nacionalidad", length=40)
    public String getFisNacionalidad() {
        return this.fisNacionalidad;
    }
    
    public void setFisNacionalidad(String fisNacionalidad) {
        this.fisNacionalidad = fisNacionalidad;
    }

    
    @Column(name="categoria", length=40)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="pasaporte", length=20)
    public String getPasaporte() {
        return this.pasaporte;
    }
    
    public void setPasaporte(String pasaporte) {
        this.pasaporte = pasaporte;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pagina_web", length=100)
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }

    
    @Column(name="comentario", length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="fis_discapacitado")
    public Boolean getFisDiscapacitado() {
        return this.fisDiscapacitado;
    }
    
    public void setFisDiscapacitado(Boolean fisDiscapacitado) {
        this.fisDiscapacitado = fisDiscapacitado;
    }

    
    @Column(name="numero", length=10)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="foto")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getTelefonoPersonas() {
        return this.telefonoPersonas;
    }
    
    public void setTelefonoPersonas(Set telefonoPersonas) {
        this.telefonoPersonas = telefonoPersonas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="parte_persona", catalog="gestionhotel", joinColumns = { 
        @JoinColumn(name="fk_persona", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="fk_parte", nullable=false, updatable=false) })
    public Set getPartes_1() {
        return this.partes_1;
    }
    
    public void setPartes_1(Set partes_1) {
        this.partes_1 = partes_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getAgencias() {
        return this.agencias;
    }
    
    public void setAgencias(Set agencias) {
        this.agencias = agencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getHuespeds() {
        return this.huespeds;
    }
    
    public void setHuespeds(Set huespeds) {
        this.huespeds = huespeds;
    }




}


