package gestionhotel.zapto.org.gestionhotelcliente.modelos.Pojos;
// Generated 09-mar-2018 17:01:24 by Hibernate Tools 4.3.1


import gestionhotel.zapto.org.gestionhotelcliente.modelos.Pojos.Usuario;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int codPersona;
     private String tipoDocumento;
     private String documentoNumero;
     private String nombre;
     private String calle;
     private String codPostal;
     private String ciudad;
     private String provincia;
     private String estado;
     private String nacionalidad;
     private Boolean jurEmpresa;
     private String jurNombreComercial;
     private String fisApellidos;
     private Date fisFechaNacimiento;
     private Integer fisEdad;
     private String fisTratamiento;
     private Integer fisCodPersona;
     private String fisCargo;
     private Boolean cliEscliente;
     private Boolean empEsempleado;
     private Usuario usuario;
     private Set parentescosForCodPersona = new HashSet(0);
     private Set detallesReservas = new HashSet(0);
     private Set reservasForCodEmpleado = new HashSet(0);
     private Set telefonoPersonas = new HashSet(0);
     private Set parentescosForCodPariente = new HashSet(0);
     private Set reservasForCodCliente = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int codPersona, String tipoDocumento, String documentoNumero, String nombre) {
        this.codPersona = codPersona;
        this.tipoDocumento = tipoDocumento;
        this.documentoNumero = documentoNumero;
        this.nombre = nombre;
    }
    public Persona(int codPersona, String tipoDocumento, String documentoNumero, String nombre, String calle, String codPostal, String ciudad, String provincia, String estado, String nacionalidad, Boolean jurEmpresa, String jurNombreComercial, String fisApellidos, Date fisFechaNacimiento, Integer fisEdad, String fisTratamiento, Integer fisCodPersona, String fisCargo, Boolean cliEscliente, Boolean empEsempleado, Usuario usuario, Set parentescosForCodPersona, Set detallesReservas, Set reservasForCodEmpleado, Set telefonoPersonas, Set parentescosForCodPariente, Set reservasForCodCliente) {
       this.codPersona = codPersona;
       this.tipoDocumento = tipoDocumento;
       this.documentoNumero = documentoNumero;
       this.nombre = nombre;
       this.calle = calle;
       this.codPostal = codPostal;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.estado = estado;
       this.nacionalidad = nacionalidad;
       this.jurEmpresa = jurEmpresa;
       this.jurNombreComercial = jurNombreComercial;
       this.fisApellidos = fisApellidos;
       this.fisFechaNacimiento = fisFechaNacimiento;
       this.fisEdad = fisEdad;
       this.fisTratamiento = fisTratamiento;
       this.fisCodPersona = fisCodPersona;
       this.fisCargo = fisCargo;
       this.cliEscliente = cliEscliente;
       this.empEsempleado = empEsempleado;
       this.usuario = usuario;
       this.parentescosForCodPersona = parentescosForCodPersona;
       this.detallesReservas = detallesReservas;
       this.reservasForCodEmpleado = reservasForCodEmpleado;
       this.telefonoPersonas = telefonoPersonas;
       this.parentescosForCodPariente = parentescosForCodPariente;
       this.reservasForCodCliente = reservasForCodCliente;
    }
   
    public int getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(int codPersona) {
        this.codPersona = codPersona;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDocumentoNumero() {
        return this.documentoNumero;
    }
    
    public void setDocumentoNumero(String documentoNumero) {
        this.documentoNumero = documentoNumero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Boolean getJurEmpresa() {
        return this.jurEmpresa;
    }
    
    public void setJurEmpresa(Boolean jurEmpresa) {
        this.jurEmpresa = jurEmpresa;
    }
    public String getJurNombreComercial() {
        return this.jurNombreComercial;
    }
    
    public void setJurNombreComercial(String jurNombreComercial) {
        this.jurNombreComercial = jurNombreComercial;
    }
    public String getFisApellidos() {
        return this.fisApellidos;
    }
    
    public void setFisApellidos(String fisApellidos) {
        this.fisApellidos = fisApellidos;
    }
    public Date getFisFechaNacimiento() {
        return this.fisFechaNacimiento;
    }
    
    public void setFisFechaNacimiento(Date fisFechaNacimiento) {
        this.fisFechaNacimiento = fisFechaNacimiento;
    }
    public Integer getFisEdad() {
        return this.fisEdad;
    }
    
    public void setFisEdad(Integer fisEdad) {
        this.fisEdad = fisEdad;
    }
    public String getFisTratamiento() {
        return this.fisTratamiento;
    }
    
    public void setFisTratamiento(String fisTratamiento) {
        this.fisTratamiento = fisTratamiento;
    }
    public Integer getFisCodPersona() {
        return this.fisCodPersona;
    }
    
    public void setFisCodPersona(Integer fisCodPersona) {
        this.fisCodPersona = fisCodPersona;
    }
    public String getFisCargo() {
        return this.fisCargo;
    }
    
    public void setFisCargo(String fisCargo) {
        this.fisCargo = fisCargo;
    }
    public Boolean getCliEscliente() {
        return this.cliEscliente;
    }
    
    public void setCliEscliente(Boolean cliEscliente) {
        this.cliEscliente = cliEscliente;
    }
    public Boolean getEmpEsempleado() {
        return this.empEsempleado;
    }
    
    public void setEmpEsempleado(Boolean empEsempleado) {
        this.empEsempleado = empEsempleado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getParentescosForCodPersona() {
        return this.parentescosForCodPersona;
    }
    
    public void setParentescosForCodPersona(Set parentescosForCodPersona) {
        this.parentescosForCodPersona = parentescosForCodPersona;
    }
    public Set getDetallesReservas() {
        return this.detallesReservas;
    }
    
    public void setDetallesReservas(Set detallesReservas) {
        this.detallesReservas = detallesReservas;
    }
    public Set getReservasForCodEmpleado() {
        return this.reservasForCodEmpleado;
    }
    
    public void setReservasForCodEmpleado(Set reservasForCodEmpleado) {
        this.reservasForCodEmpleado = reservasForCodEmpleado;
    }
    public Set getTelefonoPersonas() {
        return this.telefonoPersonas;
    }
    
    public void setTelefonoPersonas(Set telefonoPersonas) {
        this.telefonoPersonas = telefonoPersonas;
    }
    public Set getParentescosForCodPariente() {
        return this.parentescosForCodPariente;
    }
    
    public void setParentescosForCodPariente(Set parentescosForCodPariente) {
        this.parentescosForCodPariente = parentescosForCodPariente;
    }
    public Set getReservasForCodCliente() {
        return this.reservasForCodCliente;
    }
    
    public void setReservasForCodCliente(Set reservasForCodCliente) {
        this.reservasForCodCliente = reservasForCodCliente;
    }




}


