package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 24-abr-2018 21:28:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer codPersona;
     private String tipoDocumento;
     private String documentoNumero;
     private String nombre;
     private String calle;
     private String codPostal;
     private String ciudad;
     private String provincia;
     private String estado;
     private Byte esEmpresa;
     private String jurNombreComercial;
     private Date fisFechaNacimiento;
     private Integer fisEdad;
     private String fisTratamiento;
     private Integer fisCodPersona;
     private String fisCargo;
     private Byte esCliente;
     private Byte esEmpleado;
     private Byte fisSexoHombre;
     private String jurRazonSocial;
     private String fisPrimerApellido;
     private String fisSegundoApellido;
     private String fisNacionalidad;
     private String categoria;
     private String pasaporte;
     private String email;
     private String paginaWeb;
     private Date fisExpPasaporte;
     private Date fisVencPasaporte;
     private String comentario;
     private Byte fisDiscapacitado;
     private Set parentescosForCodPariente = new HashSet(0);
     private Set parentescosForCodPersona = new HashSet(0);
     private Set reservasForCodCliente = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set reservasForCodEmpleado = new HashSet(0);
     private Set reservasForAgencia = new HashSet(0);
     private Set huespedHabitacions = new HashSet(0);
     private Set telefonoPersonasForNumTelefono = new HashSet(0);
     private Set telefonoPersonasForCodPersona = new HashSet(0);

    public Persona() {
    }

    public Persona(String tipoDocumento, String documentoNumero, String nombre, String calle, String codPostal, String ciudad, String provincia, String estado, Byte esEmpresa, String jurNombreComercial, Date fisFechaNacimiento, Integer fisEdad, String fisTratamiento, Integer fisCodPersona, String fisCargo, Byte esCliente, Byte esEmpleado, Byte fisSexoHombre, String jurRazonSocial, String fisPrimerApellido, String fisSegundoApellido, String fisNacionalidad, String categoria, String pasaporte, String email, String paginaWeb, Date fisExpPasaporte, Date fisVencPasaporte, String comentario, Byte fisDiscapacitado, Set parentescosForCodPariente, Set parentescosForCodPersona, Set reservasForCodCliente, Set usuarios, Set reservasForCodEmpleado, Set reservasForAgencia, Set huespedHabitacions, Set telefonoPersonasForNumTelefono, Set telefonoPersonasForCodPersona) {
       this.tipoDocumento = tipoDocumento;
       this.documentoNumero = documentoNumero;
       this.nombre = nombre;
       this.calle = calle;
       this.codPostal = codPostal;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.estado = estado;
       this.esEmpresa = esEmpresa;
       this.jurNombreComercial = jurNombreComercial;
       this.fisFechaNacimiento = fisFechaNacimiento;
       this.fisEdad = fisEdad;
       this.fisTratamiento = fisTratamiento;
       this.fisCodPersona = fisCodPersona;
       this.fisCargo = fisCargo;
       this.esCliente = esCliente;
       this.esEmpleado = esEmpleado;
       this.fisSexoHombre = fisSexoHombre;
       this.jurRazonSocial = jurRazonSocial;
       this.fisPrimerApellido = fisPrimerApellido;
       this.fisSegundoApellido = fisSegundoApellido;
       this.fisNacionalidad = fisNacionalidad;
       this.categoria = categoria;
       this.pasaporte = pasaporte;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.fisExpPasaporte = fisExpPasaporte;
       this.fisVencPasaporte = fisVencPasaporte;
       this.comentario = comentario;
       this.fisDiscapacitado = fisDiscapacitado;
       this.parentescosForCodPariente = parentescosForCodPariente;
       this.parentescosForCodPersona = parentescosForCodPersona;
       this.reservasForCodCliente = reservasForCodCliente;
       this.usuarios = usuarios;
       this.reservasForCodEmpleado = reservasForCodEmpleado;
       this.reservasForAgencia = reservasForAgencia;
       this.huespedHabitacions = huespedHabitacions;
       this.telefonoPersonasForNumTelefono = telefonoPersonasForNumTelefono;
       this.telefonoPersonasForCodPersona = telefonoPersonasForCodPersona;
    }
   
    public Integer getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(Integer codPersona) {
        this.codPersona = codPersona;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDocumentoNumero() {
        return this.documentoNumero;
    }
    
    public void setDocumentoNumero(String documentoNumero) {
        this.documentoNumero = documentoNumero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Byte getEsEmpresa() {
        return this.esEmpresa;
    }
    
    public void setEsEmpresa(Byte esEmpresa) {
        this.esEmpresa = esEmpresa;
    }
    public String getJurNombreComercial() {
        return this.jurNombreComercial;
    }
    
    public void setJurNombreComercial(String jurNombreComercial) {
        this.jurNombreComercial = jurNombreComercial;
    }
    public Date getFisFechaNacimiento() {
        return this.fisFechaNacimiento;
    }
    
    public void setFisFechaNacimiento(Date fisFechaNacimiento) {
        this.fisFechaNacimiento = fisFechaNacimiento;
    }
    public Integer getFisEdad() {
        return this.fisEdad;
    }
    
    public void setFisEdad(Integer fisEdad) {
        this.fisEdad = fisEdad;
    }
    public String getFisTratamiento() {
        return this.fisTratamiento;
    }
    
    public void setFisTratamiento(String fisTratamiento) {
        this.fisTratamiento = fisTratamiento;
    }
    public Integer getFisCodPersona() {
        return this.fisCodPersona;
    }
    
    public void setFisCodPersona(Integer fisCodPersona) {
        this.fisCodPersona = fisCodPersona;
    }
    public String getFisCargo() {
        return this.fisCargo;
    }
    
    public void setFisCargo(String fisCargo) {
        this.fisCargo = fisCargo;
    }
    public Byte getEsCliente() {
        return this.esCliente;
    }
    
    public void setEsCliente(Byte esCliente) {
        this.esCliente = esCliente;
    }
    public Byte getEsEmpleado() {
        return this.esEmpleado;
    }
    
    public void setEsEmpleado(Byte esEmpleado) {
        this.esEmpleado = esEmpleado;
    }
    public Byte getFisSexoHombre() {
        return this.fisSexoHombre;
    }
    
    public void setFisSexoHombre(Byte fisSexoHombre) {
        this.fisSexoHombre = fisSexoHombre;
    }
    public String getJurRazonSocial() {
        return this.jurRazonSocial;
    }
    
    public void setJurRazonSocial(String jurRazonSocial) {
        this.jurRazonSocial = jurRazonSocial;
    }
    public String getFisPrimerApellido() {
        return this.fisPrimerApellido;
    }
    
    public void setFisPrimerApellido(String fisPrimerApellido) {
        this.fisPrimerApellido = fisPrimerApellido;
    }
    public String getFisSegundoApellido() {
        return this.fisSegundoApellido;
    }
    
    public void setFisSegundoApellido(String fisSegundoApellido) {
        this.fisSegundoApellido = fisSegundoApellido;
    }
    public String getFisNacionalidad() {
        return this.fisNacionalidad;
    }
    
    public void setFisNacionalidad(String fisNacionalidad) {
        this.fisNacionalidad = fisNacionalidad;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getPasaporte() {
        return this.pasaporte;
    }
    
    public void setPasaporte(String pasaporte) {
        this.pasaporte = pasaporte;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public Date getFisExpPasaporte() {
        return this.fisExpPasaporte;
    }
    
    public void setFisExpPasaporte(Date fisExpPasaporte) {
        this.fisExpPasaporte = fisExpPasaporte;
    }
    public Date getFisVencPasaporte() {
        return this.fisVencPasaporte;
    }
    
    public void setFisVencPasaporte(Date fisVencPasaporte) {
        this.fisVencPasaporte = fisVencPasaporte;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Byte getFisDiscapacitado() {
        return this.fisDiscapacitado;
    }
    
    public void setFisDiscapacitado(Byte fisDiscapacitado) {
        this.fisDiscapacitado = fisDiscapacitado;
    }
    public Set getParentescosForCodPariente() {
        return this.parentescosForCodPariente;
    }
    
    public void setParentescosForCodPariente(Set parentescosForCodPariente) {
        this.parentescosForCodPariente = parentescosForCodPariente;
    }
    public Set getParentescosForCodPersona() {
        return this.parentescosForCodPersona;
    }
    
    public void setParentescosForCodPersona(Set parentescosForCodPersona) {
        this.parentescosForCodPersona = parentescosForCodPersona;
    }
    public Set getReservasForCodCliente() {
        return this.reservasForCodCliente;
    }
    
    public void setReservasForCodCliente(Set reservasForCodCliente) {
        this.reservasForCodCliente = reservasForCodCliente;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getReservasForCodEmpleado() {
        return this.reservasForCodEmpleado;
    }
    
    public void setReservasForCodEmpleado(Set reservasForCodEmpleado) {
        this.reservasForCodEmpleado = reservasForCodEmpleado;
    }
    public Set getReservasForAgencia() {
        return this.reservasForAgencia;
    }
    
    public void setReservasForAgencia(Set reservasForAgencia) {
        this.reservasForAgencia = reservasForAgencia;
    }
    public Set getHuespedHabitacions() {
        return this.huespedHabitacions;
    }
    
    public void setHuespedHabitacions(Set huespedHabitacions) {
        this.huespedHabitacions = huespedHabitacions;
    }
    public Set getTelefonoPersonasForNumTelefono() {
        return this.telefonoPersonasForNumTelefono;
    }
    
    public void setTelefonoPersonasForNumTelefono(Set telefonoPersonasForNumTelefono) {
        this.telefonoPersonasForNumTelefono = telefonoPersonasForNumTelefono;
    }
    public Set getTelefonoPersonasForCodPersona() {
        return this.telefonoPersonasForCodPersona;
    }
    
    public void setTelefonoPersonasForCodPersona(Set telefonoPersonasForCodPersona) {
        this.telefonoPersonasForCodPersona = telefonoPersonasForCodPersona;
    }




}


