package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name="reserva"
    ,catalog="gestionhotel"
    , uniqueConstraints = {@UniqueConstraint(columnNames="codigo"), @UniqueConstraint(columnNames="voucher")} 
)
public class Reserva  implements java.io.Serializable {


     private Integer id;
     private Agencia agencia;
     private Cliente cliente;
     private Trabajador trabajador;
     private Date fecha;
     private Date fechaCancelada;
     private String motivoCancelacion;
     private String voucher;
     private String tipoTarjetaCredito;
     private String numeroTarjetaCredito;
     private String comentario;
     private String codigo;
     private Set alojamientos = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(Cliente cliente, Trabajador trabajador, Date fecha, String codigo) {
        this.cliente = cliente;
        this.trabajador = trabajador;
        this.fecha = fecha;
        this.codigo = codigo;
    }
    public Reserva(Agencia agencia, Cliente cliente, Trabajador trabajador, Date fecha, Date fechaCancelada, String motivoCancelacion, String voucher, String tipoTarjetaCredito, String numeroTarjetaCredito, String comentario, String codigo, Set alojamientos) {
       this.agencia = agencia;
       this.cliente = cliente;
       this.trabajador = trabajador;
       this.fecha = fecha;
       this.fechaCancelada = fechaCancelada;
       this.motivoCancelacion = motivoCancelacion;
       this.voucher = voucher;
       this.tipoTarjetaCredito = tipoTarjetaCredito;
       this.numeroTarjetaCredito = numeroTarjetaCredito;
       this.comentario = comentario;
       this.codigo = codigo;
       this.alojamientos = alojamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_agencia")
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_empleado", nullable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_cancelada", length=10)
    public Date getFechaCancelada() {
        return this.fechaCancelada;
    }
    
    public void setFechaCancelada(Date fechaCancelada) {
        this.fechaCancelada = fechaCancelada;
    }

    
    @Column(name="motivo_cancelacion", length=300)
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }

    
    @Column(name="voucher", unique=true, length=20)
    public String getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }

    
    @Column(name="tipo_tarjeta_credito", length=20)
    public String getTipoTarjetaCredito() {
        return this.tipoTarjetaCredito;
    }
    
    public void setTipoTarjetaCredito(String tipoTarjetaCredito) {
        this.tipoTarjetaCredito = tipoTarjetaCredito;
    }

    
    @Column(name="numero_tarjeta_credito", length=20)
    public String getNumeroTarjetaCredito() {
        return this.numeroTarjetaCredito;
    }
    
    public void setNumeroTarjetaCredito(String numeroTarjetaCredito) {
        this.numeroTarjetaCredito = numeroTarjetaCredito;
    }

    
    @Column(name="comentario", length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="codigo", unique=true, nullable=false, length=20)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reserva")
    public Set getAlojamientos() {
        return this.alojamientos;
    }
    
    public void setAlojamientos(Set alojamientos) {
        this.alojamientos = alojamientos;
    }




}


