package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 24-abr-2018 3:43:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer codReserva;
     private Persona personaByCodCliente;
     private Persona personaByCodEmpleado;
     private Date fecha;
     private Date fechaCancelada;
     private String motivoCancelacion;
     private String comentario;
     private String agencia;
     private String voucher;
     private String tipoTarjetaCredito;
     private String numeroTarjetaCredito;
     private Set detallesReservas = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(String agencia, String voucher, String tipoTarjetaCredito, String numeroTarjetaCredito) {
        this.agencia = agencia;
        this.voucher = voucher;
        this.tipoTarjetaCredito = tipoTarjetaCredito;
        this.numeroTarjetaCredito = numeroTarjetaCredito;
    }
    public Reserva(Persona personaByCodCliente, Persona personaByCodEmpleado, Date fecha, Date fechaCancelada, String motivoCancelacion, String comentario, String agencia, String voucher, String tipoTarjetaCredito, String numeroTarjetaCredito, Set detallesReservas) {
       this.personaByCodCliente = personaByCodCliente;
       this.personaByCodEmpleado = personaByCodEmpleado;
       this.fecha = fecha;
       this.fechaCancelada = fechaCancelada;
       this.motivoCancelacion = motivoCancelacion;
       this.comentario = comentario;
       this.agencia = agencia;
       this.voucher = voucher;
       this.tipoTarjetaCredito = tipoTarjetaCredito;
       this.numeroTarjetaCredito = numeroTarjetaCredito;
       this.detallesReservas = detallesReservas;
    }
   
    public Integer getCodReserva() {
        return this.codReserva;
    }
    
    public void setCodReserva(Integer codReserva) {
        this.codReserva = codReserva;
    }
    public Persona getPersonaByCodCliente() {
        return this.personaByCodCliente;
    }
    
    public void setPersonaByCodCliente(Persona personaByCodCliente) {
        this.personaByCodCliente = personaByCodCliente;
    }
    public Persona getPersonaByCodEmpleado() {
        return this.personaByCodEmpleado;
    }
    
    public void setPersonaByCodEmpleado(Persona personaByCodEmpleado) {
        this.personaByCodEmpleado = personaByCodEmpleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaCancelada() {
        return this.fechaCancelada;
    }
    
    public void setFechaCancelada(Date fechaCancelada) {
        this.fechaCancelada = fechaCancelada;
    }
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }
    public String getTipoTarjetaCredito() {
        return this.tipoTarjetaCredito;
    }
    
    public void setTipoTarjetaCredito(String tipoTarjetaCredito) {
        this.tipoTarjetaCredito = tipoTarjetaCredito;
    }
    public String getNumeroTarjetaCredito() {
        return this.numeroTarjetaCredito;
    }
    
    public void setNumeroTarjetaCredito(String numeroTarjetaCredito) {
        this.numeroTarjetaCredito = numeroTarjetaCredito;
    }
    public Set getDetallesReservas() {
        return this.detallesReservas;
    }
    
    public void setDetallesReservas(Set detallesReservas) {
        this.detallesReservas = detallesReservas;
    }




}


