package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int codReserva;
     private Persona personaByCodEmpleado;
     private Persona personaByCodCliente;
     private Date fecha;
     private Date fechaCancelada;
     private String motivoCancelacion;
     private String comentario;
     private Set detallesReservas = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int codReserva, Persona personaByCodEmpleado, Persona personaByCodCliente, Date fecha) {
        this.codReserva = codReserva;
        this.personaByCodEmpleado = personaByCodEmpleado;
        this.personaByCodCliente = personaByCodCliente;
        this.fecha = fecha;
    }
    public Reserva(int codReserva, Persona personaByCodEmpleado, Persona personaByCodCliente, Date fecha, Date fechaCancelada, String motivoCancelacion, String comentario, Set detallesReservas) {
       this.codReserva = codReserva;
       this.personaByCodEmpleado = personaByCodEmpleado;
       this.personaByCodCliente = personaByCodCliente;
       this.fecha = fecha;
       this.fechaCancelada = fechaCancelada;
       this.motivoCancelacion = motivoCancelacion;
       this.comentario = comentario;
       this.detallesReservas = detallesReservas;
    }
   
    public int getCodReserva() {
        return this.codReserva;
    }
    
    public void setCodReserva(int codReserva) {
        this.codReserva = codReserva;
    }
    public Persona getPersonaByCodEmpleado() {
        return this.personaByCodEmpleado;
    }
    
    public void setPersonaByCodEmpleado(Persona personaByCodEmpleado) {
        this.personaByCodEmpleado = personaByCodEmpleado;
    }
    public Persona getPersonaByCodCliente() {
        return this.personaByCodCliente;
    }
    
    public void setPersonaByCodCliente(Persona personaByCodCliente) {
        this.personaByCodCliente = personaByCodCliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaCancelada() {
        return this.fechaCancelada;
    }
    
    public void setFechaCancelada(Date fechaCancelada) {
        this.fechaCancelada = fechaCancelada;
    }
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Set getDetallesReservas() {
        return this.detallesReservas;
    }
    
    public void setDetallesReservas(Set detallesReservas) {
        this.detallesReservas = detallesReservas;
    }




}


