package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Situacion generated by hbm2java
 */
public class Situacion  implements java.io.Serializable {


     private int idSituacion;
     private String descripcion;
     private Set estadoHabitacions = new HashSet(0);

    public Situacion() {
    }

	
    public Situacion(int idSituacion, String descripcion) {
        this.idSituacion = idSituacion;
        this.descripcion = descripcion;
    }
    public Situacion(int idSituacion, String descripcion, Set estadoHabitacions) {
       this.idSituacion = idSituacion;
       this.descripcion = descripcion;
       this.estadoHabitacions = estadoHabitacions;
    }
   
    public int getIdSituacion() {
        return this.idSituacion;
    }
    
    public void setIdSituacion(int idSituacion) {
        this.idSituacion = idSituacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEstadoHabitacions() {
        return this.estadoHabitacions;
    }
    
    public void setEstadoHabitacions(Set estadoHabitacions) {
        this.estadoHabitacions = estadoHabitacions;
    }




}


