package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="gestionhotel"
)
public class Telefono  implements java.io.Serializable {


     private String numero;
     private String descripcion;
     private String tipo;
     private String comentario;
     private Set telefonoPersonas = new HashSet(0);

    public Telefono() {
    }

	
    public Telefono(String numero, String tipo, String comentario) {
        this.numero = numero;
        this.tipo = tipo;
        this.comentario = comentario;
    }
    public Telefono(String numero, String descripcion, String tipo, String comentario, Set telefonoPersonas) {
       this.numero = numero;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.comentario = comentario;
       this.telefonoPersonas = telefonoPersonas;
    }
   
     @Id 

    
    @Column(name="numero", unique=true, nullable=false, length=15)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="descripcion", length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="tipo", nullable=false, length=40)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="comentario", nullable=false, length=300)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="telefono")
    public Set getTelefonoPersonas() {
        return this.telefonoPersonas;
    }
    
    public void setTelefonoPersonas(Set telefonoPersonas) {
        this.telefonoPersonas = telefonoPersonas;
    }




}


