package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 05-jun-2018 18:15:23 by Hibernate Tools 4.3.1



/**
 * TelefonoPersonaId generated by hbm2java
 */
public class TelefonoPersonaId  implements java.io.Serializable {


     private int codPersona;
     private String numTelefono;

    public TelefonoPersonaId() {
    }

    public TelefonoPersonaId(int codPersona, String numTelefono) {
       this.codPersona = codPersona;
       this.numTelefono = numTelefono;
    }
   
    public int getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(int codPersona) {
        this.codPersona = codPersona;
    }
    public String getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonoPersonaId) ) return false;
		 TelefonoPersonaId castOther = ( TelefonoPersonaId ) other; 
         
		 return (this.getCodPersona()==castOther.getCodPersona())
 && ( (this.getNumTelefono()==castOther.getNumTelefono()) || ( this.getNumTelefono()!=null && castOther.getNumTelefono()!=null && this.getNumTelefono().equals(castOther.getNumTelefono()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodPersona();
         result = 37 * result + ( getNumTelefono() == null ? 0 : this.getNumTelefono().hashCode() );
         return result;
   }   


}


