package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1



/**
 * TelefonoPersonaId generated by hbm2java
 */
public class TelefonoPersonaId  implements java.io.Serializable {


     private int codPersona;
     private int numTelefono;

    public TelefonoPersonaId() {
    }

    public TelefonoPersonaId(int codPersona, int numTelefono) {
       this.codPersona = codPersona;
       this.numTelefono = numTelefono;
    }
   
    public int getCodPersona() {
        return this.codPersona;
    }
    
    public void setCodPersona(int codPersona) {
        this.codPersona = codPersona;
    }
    public int getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(int numTelefono) {
        this.numTelefono = numTelefono;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonoPersonaId) ) return false;
		 TelefonoPersonaId castOther = ( TelefonoPersonaId ) other; 
         
		 return (this.getCodPersona()==castOther.getCodPersona())
 && (this.getNumTelefono()==castOther.getNumTelefono());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodPersona();
         result = 37 * result + this.getNumTelefono();
         return result;
   }   


}


