package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelefonoPersona generated by hbm2java
 */
@Entity
@Table(name="telefono_persona"
    ,catalog="gestionhotel"
)
public class TelefonoPersona  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private Telefono telefono;

    public TelefonoPersona() {
    }

    public TelefonoPersona(Persona persona, Telefono telefono) {
       this.persona = persona;
       this.telefono = telefono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numero", nullable=false)
    public Telefono getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Telefono telefono) {
        this.telefono = telefono;
    }




}


