package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 02-jun-2018 20:17:43 by Hibernate Tools 4.3.1



/**
 * TelefonoPersona generated by hbm2java
 */
public class TelefonoPersona  implements java.io.Serializable {


     private TelefonoPersonaId id;
     private Persona persona;
     private String descripcion;
     private String tipo;
     private String comentario;

    public TelefonoPersona() {
    }

	
    public TelefonoPersona(TelefonoPersonaId id, Persona persona, String tipo, String comentario) {
        this.id = id;
        this.persona = persona;
        this.tipo = tipo;
        this.comentario = comentario;
    }
    public TelefonoPersona(TelefonoPersonaId id, Persona persona, String descripcion, String tipo, String comentario) {
       this.id = id;
       this.persona = persona;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.comentario = comentario;
    }
   
    public TelefonoPersonaId getId() {
        return this.id;
    }
    
    public void setId(TelefonoPersonaId id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


