package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoHabitacion generated by hbm2java
 */
@Entity
@Table(name="tipo_habitacion"
    ,catalog="gestionhotel"
)
public class TipoHabitacion  implements java.io.Serializable {


     private int id;
     private int descripcion;

    public TipoHabitacion() {
    }

    public TipoHabitacion(int id, int descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", nullable=false)
    public int getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(int descripcion) {
        this.descripcion = descripcion;
    }




}


