package gestionhotel.zapto.org.gestionhotelcliente.modelos.Pojos;
// Generated 09-mar-2018 17:01:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private int idTipo;
     private String descripcion;
     private Set habitacions = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(int idTipo, String descripcion) {
        this.idTipo = idTipo;
        this.descripcion = descripcion;
    }
    public Tipo(int idTipo, String descripcion, Set habitacions) {
       this.idTipo = idTipo;
       this.descripcion = descripcion;
       this.habitacions = habitacions;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


