package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 09-jun-2018 9:28:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trabajador generated by hbm2java
 */
@Entity
@Table(name="trabajador"
    ,catalog="gestionhotel"
)
public class Trabajador  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private boolean dentro;
     private String departamento;
     private String usuario;
     private String password;
     private String sector;
     private String rol;
     private Set facturas = new HashSet(0);
     private Set partes = new HashSet(0);
     private Set habitacions = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Trabajador() {
    }

	
    public Trabajador(Persona persona, boolean dentro, String departamento, String usuario, String password, String sector, String rol) {
        this.persona = persona;
        this.dentro = dentro;
        this.departamento = departamento;
        this.usuario = usuario;
        this.password = password;
        this.sector = sector;
        this.rol = rol;
    }
    public Trabajador(Persona persona, boolean dentro, String departamento, String usuario, String password, String sector, String rol, Set facturas, Set partes, Set habitacions, Set reservas) {
       this.persona = persona;
       this.dentro = dentro;
       this.departamento = departamento;
       this.usuario = usuario;
       this.password = password;
       this.sector = sector;
       this.rol = rol;
       this.facturas = facturas;
       this.partes = partes;
       this.habitacions = habitacions;
       this.reservas = reservas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="dentro", nullable=false)
    public boolean isDentro() {
        return this.dentro;
    }
    
    public void setDentro(boolean dentro) {
        this.dentro = dentro;
    }

    
    @Column(name="departamento", nullable=false, length=40)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="usuario", nullable=false, length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="sector", nullable=false, length=40)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }

    
    @Column(name="rol", nullable=false, length=20)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajador")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajador")
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajador")
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajador")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


