package gestionhotel.zapto.org.gestionhotelcliente.modelos.pojos;
// Generated 13-mar-2018 20:11:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codUsuario;
     private Persona persona;
     private String nombreUsuario;
     private String passUsuario;
     private Boolean bloqueado;
     private Date ultimaActividad;
     private Date fechaCaducidad;

    public Usuario() {
    }

	
    public Usuario(Persona persona, String nombreUsuario, String passUsuario) {
        this.persona = persona;
        this.nombreUsuario = nombreUsuario;
        this.passUsuario = passUsuario;
    }
    public Usuario(Persona persona, String nombreUsuario, String passUsuario, Boolean bloqueado, Date ultimaActividad, Date fechaCaducidad) {
       this.persona = persona;
       this.nombreUsuario = nombreUsuario;
       this.passUsuario = passUsuario;
       this.bloqueado = bloqueado;
       this.ultimaActividad = ultimaActividad;
       this.fechaCaducidad = fechaCaducidad;
    }
   
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }
    public Boolean getBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(Boolean bloqueado) {
        this.bloqueado = bloqueado;
    }
    public Date getUltimaActividad() {
        return this.ultimaActividad;
    }
    
    public void setUltimaActividad(Date ultimaActividad) {
        this.ultimaActividad = ultimaActividad;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }




}


